### ISSUE TITLE
Protocol 2000 command ending in \n not a \r

### ISSUE THREAD

**Issue by EventReplay** [bitfocus/companion-module-kramer-matrix#1]
@SteveTherrien I'm trying to help here:
https://github.com/bitfocus/companion-module-requests/issues/150
I've had a look through your code and I think I can see a possible issue in this line of code:
0x0a  // End with a \r to separate multiple commands
\r carriage return is 0x0d \n line feed is 0x0a.
I've testing on my VS-42HDMI with a recent version of v2 and that seems to work fine so I'm a little confused. I do remember reading somewhere \r then assumes \n but that might have been extron.
Could you offer any advise?
Many Thanks
Regards
Nigel

**Comment by SteveTherrien** [comment]
@EventReplay Good catch on the bad comment (or bad code, depending on which way you look at it).

During development I remember having trouble if multiple commands were sent too quickly, and adding a 0a (or 0d) solved it. Today I brought home an old VS-66HDCP from work and it accepts commands with a 0a, 0d, or no terminating character at all. 

[Your comment](https://github.com/bitfocus/companion-module-requests/issues/150#issuecomment-578330443) about your VS-42HDMI and @dmxking512's testing with a VS-311H mirrors what I'm seeing here, so I'm going to remove the problematic fifth byte.

**Comment by dmxking512** [comment]
@SteveTherrien Many thanks for the quick turn around! 

Stupid question... what happens now haha? will i need to reinstall companion or download an updated version? or does it simply pull the updated code from Github on launch? 

Many Thanks again!

**Comment by JeffreyDavidsz** [comment]
@dmxking512 I've updated the core so downloading the build from the site should be enough to do it! (and of course reinstall that version on you PC/MAC)

**Comment by dmxking512** [comment]
@JeffreyDavidsz Direct from the Bitfocus website? or from github? 

The bitfocus website shows:
Companion
Version: 1.4.0
Updated: 2019-Sep-13

Many thanks
Sam

**Comment by JeffreyDavidsz** [comment]
There is a link just below that says: 2.0 beta

**Comment by dmxking512** [comment]
Amazing :D thankyou. Many thanks all I can confirm that this version does work with the VS-311H 👍
